### ISSUE TITLE
BF Instance Display - BF Item Link and BF Item SameAs link display tool-tip

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/alliance-bibcat#10]
In the BF Instance display, the link-out to the ILS or Discovery Layer (indivItem.sameAs) should have a tool-tip or other alt tag that displays "Link to Catalog" while the indiviItem.iri link should have "More Information..."

**Comment by swalker76** [comment]
Tool Tips are displaying in development release as of 9/18/17
