### ISSUE TITLE
Google and robots.txt file

### ISSUE THREAD

**Issue by swalker76** [KnowledgeLinks/alliance-bibcat#15]
Our Google Search Console reports the following on August 22:

robots.txt fetch failed
You have a robots.txt file that we are currently unable to fetch. In such cases we stop crawling your site until we get hold of a robots.txt, or fall back to the last known good robots.txt file.

I can open it in a web browser - looks like this "User-agent: * Disallow:"

**Comment by jermnelson** [comment]
Found this [stackoverflow](https://stackoverflow.com/questions/20819569/robots-txt-error-content-type-should-be-text-plain) response that the Content-Type for _robots.txt_ should be `text/plain`. In [commit](https://github.com/KnowledgeLinks/alliance-bibcat/commit/61124cc3c0e41728b207c1ecc64c88c0d26eff9b), added new route that returns robots.txt with the `text/plain` content-type.

**Comment by swalker76** [comment]
Issue is now resolved.
