### ISSUE TITLE
SUNY Buffalo Item Records - Map Wrong

### ISSUE THREAD

**Issue by swalker76** [KnowledgeLinks/alliance-bibcat#24]
Current item records for SUNY Buffalo show a generic map.  Should point to map with their location.

**Comment by mstabile75** [comment]
fixed in commit https://github.com/KnowledgeLinks/alliance-bibcat/commit/c503dfd2f18ebb39b79a3f06ab77c9c0ba12945c

Google maps API call in the item template was not sending city and state

**Comment by mstabile75** [comment]
Approved by Steve
