### ISSUE TITLE
Multiple Item's not showing up in Instance View

### ISSUE THREAD

**Issue by jermnelson** [KnowledgeLinks/alliance-bibcat#6]
The instance [What is Islam? : the importance of being Islamic](https://bibcat.coalliance.org/what-is-islam-the-importance-of-being-islamic) should have items from SUNY Buffalo, Colorado College, and the University of Colorado Boulder. Currently only showing one Item.

**Comment by swalker76** [comment]
Jeremy - This item is only showing Colorado College and SUNY Buffalo items, no CUB item shows.

**Comment by swalker76** [comment]
The display lists the items in this order: Colorado College, SUNY Buffalo, SUNY Buffalo, Colorado College.  Can the items be grouped by institution instead?

**Comment by swalker76** [comment]
Tested 11/15/17 - looks good
